spring:
  application:
    name: edge-service
  cloud:
    discovery:
      enabled: true
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transaction/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

server:
  port: 8888