spring:
  application:
    name: discovery-server

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    preferIpAddress: true
  server:
    wait-time-in-ms-when-sync-empty: 1000
